version: '3.7'
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
