export { default as Jumbotron } from './jumbotron';
export { default as Footer } from './footer';
export { default as OptForm } from './opt-form';
export { default as Header } from './header';
export { default as Form } from './form';
export { default as Dashboard } from './dashboard';
export { default as Board } from './board';
export { default as Sidebar } from './sidebar';
export { default as InnerPage } from './innerpage';
